// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: trip_command.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UpdateTripInformation_MatchTrip_FullMethodName    = "/trip.UpdateTripInformation/MatchTrip"
	UpdateTripInformation_StartTrip_FullMethodName    = "/trip.UpdateTripInformation/StartTrip"
	UpdateTripInformation_CompleteTrip_FullMethodName = "/trip.UpdateTripInformation/CompleteTrip"
	UpdateTripInformation_CancelTrip_FullMethodName   = "/trip.UpdateTripInformation/CancelTrip"
)

// UpdateTripInformationClient is the client API for UpdateTripInformation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdateTripInformationClient interface {
	MatchTrip(ctx context.Context, in *TripActionRequest, opts ...grpc.CallOption) (*TripResponse, error)
	StartTrip(ctx context.Context, in *TripActionRequest, opts ...grpc.CallOption) (*TripResponse, error)
	CompleteTrip(ctx context.Context, in *TripActionRequest, opts ...grpc.CallOption) (*TripResponse, error)
	CancelTrip(ctx context.Context, in *CancelTripRequest, opts ...grpc.CallOption) (*TripResponse, error)
}

type updateTripInformationClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdateTripInformationClient(cc grpc.ClientConnInterface) UpdateTripInformationClient {
	return &updateTripInformationClient{cc}
}

func (c *updateTripInformationClient) MatchTrip(ctx context.Context, in *TripActionRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, UpdateTripInformation_MatchTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateTripInformationClient) StartTrip(ctx context.Context, in *TripActionRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, UpdateTripInformation_StartTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateTripInformationClient) CompleteTrip(ctx context.Context, in *TripActionRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, UpdateTripInformation_CompleteTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updateTripInformationClient) CancelTrip(ctx context.Context, in *CancelTripRequest, opts ...grpc.CallOption) (*TripResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TripResponse)
	err := c.cc.Invoke(ctx, UpdateTripInformation_CancelTrip_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdateTripInformationServer is the server API for UpdateTripInformation service.
// All implementations must embed UnimplementedUpdateTripInformationServer
// for forward compatibility.
type UpdateTripInformationServer interface {
	MatchTrip(context.Context, *TripActionRequest) (*TripResponse, error)
	StartTrip(context.Context, *TripActionRequest) (*TripResponse, error)
	CompleteTrip(context.Context, *TripActionRequest) (*TripResponse, error)
	CancelTrip(context.Context, *CancelTripRequest) (*TripResponse, error)
	mustEmbedUnimplementedUpdateTripInformationServer()
}

// UnimplementedUpdateTripInformationServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUpdateTripInformationServer struct{}

func (UnimplementedUpdateTripInformationServer) MatchTrip(context.Context, *TripActionRequest) (*TripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MatchTrip not implemented")
}
func (UnimplementedUpdateTripInformationServer) StartTrip(context.Context, *TripActionRequest) (*TripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartTrip not implemented")
}
func (UnimplementedUpdateTripInformationServer) CompleteTrip(context.Context, *TripActionRequest) (*TripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTrip not implemented")
}
func (UnimplementedUpdateTripInformationServer) CancelTrip(context.Context, *CancelTripRequest) (*TripResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelTrip not implemented")
}
func (UnimplementedUpdateTripInformationServer) mustEmbedUnimplementedUpdateTripInformationServer() {}
func (UnimplementedUpdateTripInformationServer) testEmbeddedByValue()                               {}

// UnsafeUpdateTripInformationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdateTripInformationServer will
// result in compilation errors.
type UnsafeUpdateTripInformationServer interface {
	mustEmbedUnimplementedUpdateTripInformationServer()
}

func RegisterUpdateTripInformationServer(s grpc.ServiceRegistrar, srv UpdateTripInformationServer) {
	// If the following call panics, it indicates UnimplementedUpdateTripInformationServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UpdateTripInformation_ServiceDesc, srv)
}

func _UpdateTripInformation_MatchTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TripActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateTripInformationServer).MatchTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateTripInformation_MatchTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateTripInformationServer).MatchTrip(ctx, req.(*TripActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpdateTripInformation_StartTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TripActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateTripInformationServer).StartTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateTripInformation_StartTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateTripInformationServer).StartTrip(ctx, req.(*TripActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpdateTripInformation_CompleteTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TripActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateTripInformationServer).CompleteTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateTripInformation_CompleteTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateTripInformationServer).CompleteTrip(ctx, req.(*TripActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UpdateTripInformation_CancelTrip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTripRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdateTripInformationServer).CancelTrip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UpdateTripInformation_CancelTrip_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdateTripInformationServer).CancelTrip(ctx, req.(*CancelTripRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UpdateTripInformation_ServiceDesc is the grpc.ServiceDesc for UpdateTripInformation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UpdateTripInformation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "trip.UpdateTripInformation",
	HandlerType: (*UpdateTripInformationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MatchTrip",
			Handler:    _UpdateTripInformation_MatchTrip_Handler,
		},
		{
			MethodName: "StartTrip",
			Handler:    _UpdateTripInformation_StartTrip_Handler,
		},
		{
			MethodName: "CompleteTrip",
			Handler:    _UpdateTripInformation_CompleteTrip_Handler,
		},
		{
			MethodName: "CancelTrip",
			Handler:    _UpdateTripInformation_CancelTrip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trip_command.proto",
}
