// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/trip_command.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseStatus int32

const (
	ResponseStatus_SUCCESS   ResponseStatus = 0
	ResponseStatus_UNSUCCESS ResponseStatus = 1
)

// Enum value maps for ResponseStatus.
var (
	ResponseStatus_name = map[int32]string{
		0: "SUCCESS",
		1: "UNSUCCESS",
	}
	ResponseStatus_value = map[string]int32{
		"SUCCESS":   0,
		"UNSUCCESS": 1,
	}
)

func (x ResponseStatus) Enum() *ResponseStatus {
	p := new(ResponseStatus)
	*p = x
	return p
}

func (x ResponseStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResponseStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_trip_command_proto_enumTypes[0].Descriptor()
}

func (ResponseStatus) Type() protoreflect.EnumType {
	return &file_proto_trip_command_proto_enumTypes[0]
}

func (x ResponseStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResponseStatus.Descriptor instead.
func (ResponseStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_trip_command_proto_rawDescGZIP(), []int{0}
}

type TripActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripActionRequest) Reset() {
	*x = TripActionRequest{}
	mi := &file_proto_trip_command_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripActionRequest) ProtoMessage() {}

func (x *TripActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_command_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripActionRequest.ProtoReflect.Descriptor instead.
func (*TripActionRequest) Descriptor() ([]byte, []int) {
	return file_proto_trip_command_proto_rawDescGZIP(), []int{0}
}

func (x *TripActionRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *TripActionRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type CancelTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	IdCancelledBy string                 `protobuf:"bytes,2,opt,name=id_cancelled_by,json=idCancelledBy,proto3" json:"id_cancelled_by,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTripRequest) Reset() {
	*x = CancelTripRequest{}
	mi := &file_proto_trip_command_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTripRequest) ProtoMessage() {}

func (x *CancelTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_command_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTripRequest.ProtoReflect.Descriptor instead.
func (*CancelTripRequest) Descriptor() ([]byte, []int) {
	return file_proto_trip_command_proto_rawDescGZIP(), []int{1}
}

func (x *CancelTripRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *CancelTripRequest) GetIdCancelledBy() string {
	if x != nil {
		return x.IdCancelledBy
	}
	return ""
}

func (x *CancelTripRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type NoDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NoDriverRequest) Reset() {
	*x = NoDriverRequest{}
	mi := &file_proto_trip_command_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NoDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoDriverRequest) ProtoMessage() {}

func (x *NoDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_command_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoDriverRequest.ProtoReflect.Descriptor instead.
func (*NoDriverRequest) Descriptor() ([]byte, []int) {
	return file_proto_trip_command_proto_rawDescGZIP(), []int{2}
}

func (x *NoDriverRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type TripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	Status        ResponseStatus         `protobuf:"varint,2,opt,name=status,proto3,enum=trip.ResponseStatus" json:"status,omitempty"`
	Message       *string                `protobuf:"bytes,3,opt,name=message,proto3,oneof" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripResponse) Reset() {
	*x = TripResponse{}
	mi := &file_proto_trip_command_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripResponse) ProtoMessage() {}

func (x *TripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_trip_command_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripResponse.ProtoReflect.Descriptor instead.
func (*TripResponse) Descriptor() ([]byte, []int) {
	return file_proto_trip_command_proto_rawDescGZIP(), []int{3}
}

func (x *TripResponse) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *TripResponse) GetStatus() ResponseStatus {
	if x != nil {
		return x.Status
	}
	return ResponseStatus_SUCCESS
}

func (x *TripResponse) GetMessage() string {
	if x != nil && x.Message != nil {
		return *x.Message
	}
	return ""
}

var File_proto_trip_command_proto protoreflect.FileDescriptor

const file_proto_trip_command_proto_rawDesc = "" +
	"\n" +
	"\x18proto/trip_command.proto\x12\x04trip\"I\n" +
	"\x11TripActionRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"l\n" +
	"\x11CancelTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12&\n" +
	"\x0fid_cancelled_by\x18\x02 \x01(\tR\ridCancelledBy\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"*\n" +
	"\x0fNoDriverRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\"\x80\x01\n" +
	"\fTripResponse\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12,\n" +
	"\x06status\x18\x02 \x01(\x0e2\x14.trip.ResponseStatusR\x06status\x12\x1d\n" +
	"\amessage\x18\x03 \x01(\tH\x00R\amessage\x88\x01\x01B\n" +
	"\n" +
	"\b_message*,\n" +
	"\x0eResponseStatus\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\r\n" +
	"\tUNSUCCESS\x10\x012\xbf\x02\n" +
	"\x15UpdateTripInformation\x128\n" +
	"\tMatchTrip\x12\x17.trip.TripActionRequest\x1a\x12.trip.TripResponse\x128\n" +
	"\tStartTrip\x12\x17.trip.TripActionRequest\x1a\x12.trip.TripResponse\x12;\n" +
	"\fCompleteTrip\x12\x17.trip.TripActionRequest\x1a\x12.trip.TripResponse\x129\n" +
	"\n" +
	"CancelTrip\x12\x17.trip.CancelTripRequest\x1a\x12.trip.TripResponse\x12:\n" +
	"\rNoDriverFound\x12\x15.trip.NoDriverRequest\x1a\x12.trip.TripResponseB\x1d\n" +
	"\x0fcom.goride.grpcP\x01Z\b./pkg/pbb\x06proto3"

var (
	file_proto_trip_command_proto_rawDescOnce sync.Once
	file_proto_trip_command_proto_rawDescData []byte
)

func file_proto_trip_command_proto_rawDescGZIP() []byte {
	file_proto_trip_command_proto_rawDescOnce.Do(func() {
		file_proto_trip_command_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_trip_command_proto_rawDesc), len(file_proto_trip_command_proto_rawDesc)))
	})
	return file_proto_trip_command_proto_rawDescData
}

var file_proto_trip_command_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_trip_command_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_trip_command_proto_goTypes = []any{
	(ResponseStatus)(0),       // 0: trip.ResponseStatus
	(*TripActionRequest)(nil), // 1: trip.TripActionRequest
	(*CancelTripRequest)(nil), // 2: trip.CancelTripRequest
	(*NoDriverRequest)(nil),   // 3: trip.NoDriverRequest
	(*TripResponse)(nil),      // 4: trip.TripResponse
}
var file_proto_trip_command_proto_depIdxs = []int32{
	0, // 0: trip.TripResponse.status:type_name -> trip.ResponseStatus
	1, // 1: trip.UpdateTripInformation.MatchTrip:input_type -> trip.TripActionRequest
	1, // 2: trip.UpdateTripInformation.StartTrip:input_type -> trip.TripActionRequest
	1, // 3: trip.UpdateTripInformation.CompleteTrip:input_type -> trip.TripActionRequest
	2, // 4: trip.UpdateTripInformation.CancelTrip:input_type -> trip.CancelTripRequest
	3, // 5: trip.UpdateTripInformation.NoDriverFound:input_type -> trip.NoDriverRequest
	4, // 6: trip.UpdateTripInformation.MatchTrip:output_type -> trip.TripResponse
	4, // 7: trip.UpdateTripInformation.StartTrip:output_type -> trip.TripResponse
	4, // 8: trip.UpdateTripInformation.CompleteTrip:output_type -> trip.TripResponse
	4, // 9: trip.UpdateTripInformation.CancelTrip:output_type -> trip.TripResponse
	4, // 10: trip.UpdateTripInformation.NoDriverFound:output_type -> trip.TripResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_trip_command_proto_init() }
func file_proto_trip_command_proto_init() {
	if File_proto_trip_command_proto != nil {
		return
	}
	file_proto_trip_command_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_trip_command_proto_rawDesc), len(file_proto_trip_command_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_trip_command_proto_goTypes,
		DependencyIndexes: file_proto_trip_command_proto_depIdxs,
		EnumInfos:         file_proto_trip_command_proto_enumTypes,
		MessageInfos:      file_proto_trip_command_proto_msgTypes,
	}.Build()
	File_proto_trip_command_proto = out.File
	file_proto_trip_command_proto_goTypes = nil
	file_proto_trip_command_proto_depIdxs = nil
}
