ALTER TABLE trips 
ALTER COLUMN pickup_lat TYPE DOUBLE PRECISION,
ALTER COLUMN pickup_lng TYPE DOUBLE PRECISION,
ALTER COLUMN dropoff_lat TYPE DOUBLE PRECISION,
ALTER COLUMN dropoff_lng TYPE DOUBLE PRECISION,
ALTER COLUMN total_amount TYPE DECIMAL(15,2),
ALTER COLUMN driver_earning TYPE DECIMAL(15,2);

