services:
    rabbitmq:
        image: rabbitmq:4.3.4-management-alpine
        ports:
            - "5672:5672"
            - "15672:15672"
        environment:
            - RABBITMQ_DEFAULT_USER=${SERVICE_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq

    api-gateway:
        image: nginx:1.31.4-alpine
        ports:
            - "80:80"
        volumes:
            - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf:ro
        depends_on:
            - trip-service
            - location-service

volumes:
    rabbitmq_data: 

include:
    - location-service/docker-compose.yaml
    - trip-service/docker-compose.yaml